# name: Terraform Apply

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main  

# jobs:
#   aws: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Setup AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1 
#   terraform: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
#       - name: Download Terraform Plan Artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: terraform-plan
#       - name: Terraform Apply
#         run: terraform apply -auto-approve terraform.tfplan
#     needs: aws