# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = { "environment" : "dev", "managed_by" : "terragrunt", "owner" : "data-eng", "project" : "event-driven-etl" }
  }
}
